# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73f026bed828c4a93cea015ad4251514f50ae45b1192fa89bee7e88544cf7963e39b9ab0d98cedd09be8bc3108b311c99aba7d3f63989d41d9815a1aae7e12db

test:
  secret_key_base: 1acffbde9fefed51e161176d8be8065924b5b53e27d0683c16628db61b46203f539a0382b80bfd768e38ad17d669e3390cab9975c4482e38ebf485727c443b58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
